import AppKit
import ApplicationServices
import Carbon            // IsSecureEventInputEnabled
import CoreGraphics

/// Result of an insertion attempt, consumed by `DictationController`.
enum InsertOutcome: Equatable, Sendable {
    enum FailureReason: Equatable, Sendable {
        case pasteboardWriteFailed
        case pasteShortcutFailed
        case cancelled
    }

    case inserted
    case secureInputBlocked
    case noAccessibilityPermission
    case failed(FailureReason)
}

/// Inserts transcribed text at the cursor of whatever app is focused.
///
/// Strategy (matching VoiceInk, the only method that works across native Cocoa,
/// browsers, Electron and terminals): put the text on the pasteboard, synthesise
/// ⌘V, then restore the previous pasteboard contents. Restoration is guarded by a
/// per-session marker so it never clobbers something the user copied in between,
/// and only runs when `settings.restoreClipboard` is on.
///
/// No AX-write path: `kAXSelectedTextAttribute` is unreliable on Chromium/Electron
/// and terminals and caps out around 2040 characters, so it is deliberately absent.
@MainActor
final class TextInserter {

    private let settings: SettingsStore

    // Session marker + nspasteboard.org transient types. Clipboard managers
    // (Paste, Maccy, Raycast) skip the transient-tagged entry; the session UUID
    // lets us prove the pasteboard is still ours before restoring.
    private let sessionType   = NSPasteboard.PasteboardType("com.modict.PasteSession")
    private let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private let autoGenType   = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    private let sourceType    = NSPasteboard.PasteboardType("org.nspasteboard.source")

    // Timings validated against VoiceInk's paste pipeline.
    private static let prePasteDelay: UInt64        = 100_000_000   // 0.10 s
    private static let interEventDelay: UInt64       = 10_000_000   // 0.01 s
    private static let clipboardRestoreDelay: UInt64 = 250_000_000  // 0.25 s

    // Carbon virtual key codes.
    private static let keyCommand: CGKeyCode = 0x37
    private static let keyV: CGKeyCode       = 0x09

    init(settings: SettingsStore) {
        self.settings = settings
    }

    func insert(_ text: String) async -> InsertOutcome {
        guard !text.isEmpty else { return .inserted }
        guard !Task.isCancelled else { return .failed(.cancelled) }

        // Secure input (password fields, Terminal's Secure Keyboard Entry) blocks
        // event taps, synthetic events and AX alike — bail before a silent failure.
        if IsSecureEventInputEnabled() { return .secureInputBlocked }

        // Posting ⌘V requires the Accessibility grant; without it nothing is delivered.
        guard AXIsProcessTrusted() else { return .noAccessibilityPermission }

        let pasteboard = NSPasteboard.general
        let restore = settings.restoreClipboard
        let snapshot = restore ? snapshotItems(pasteboard) : []
        let sessionID = UUID().uuidString

        guard !Task.isCancelled else { return .failed(.cancelled) }
        guard writeText(text, sessionID: sessionID, restore: restore, to: pasteboard) else {
            return .failed(.pasteboardWriteFailed)
        }

        try? await Task.sleep(nanoseconds: Self.prePasteDelay)
        guard !Task.isCancelled else {
            restoreIfStillOurs(text: text, sessionID: sessionID, snapshot: snapshot, to: pasteboard)
            return .failed(.cancelled)
        }

        guard await postCommandV() else { return .failed(.pasteShortcutFailed) }
        guard !Task.isCancelled else { return .failed(.cancelled) }

        if restore {
            try? await Task.sleep(nanoseconds: Self.clipboardRestoreDelay)
            guard !Task.isCancelled else {
                restoreIfStillOurs(text: text, sessionID: sessionID, snapshot: snapshot, to: pasteboard)
                return .failed(.cancelled)
            }
            restoreIfStillOurs(text: text, sessionID: sessionID, snapshot: snapshot, to: pasteboard)
        }

        return .inserted
    }

    // MARK: - Pasteboard

    /// Every item as its (type, Data) pairs so arbitrary flavors survive the round-trip.
    private func snapshotItems(_ pasteboard: NSPasteboard) -> [[(NSPasteboard.PasteboardType, Data)]] {
        (pasteboard.pasteboardItems ?? []).map { item in
            item.types.compactMap { type in
                item.data(forType: type).map { (type, $0) }
            }
        }
    }

    private func writeText(_ text: String,
                           sessionID: String,
                           restore: Bool,
                           to pasteboard: NSPasteboard) -> Bool {
        pasteboard.clearContents()
        guard pasteboard.setString(text, forType: .string) else { return false }
        if let bundleID = Bundle.main.bundleIdentifier {
            pasteboard.setString(bundleID, forType: sourceType)
        }
        if restore {
            // Transient markers keep clipboard managers from recording the paste;
            // the session UUID is what we check before restoring.
            pasteboard.setData(Data(), forType: transientType)
            pasteboard.setData(Data(), forType: autoGenType)
            pasteboard.setString(sessionID, forType: sessionType)
        }
        return true
    }

    /// Restore only if the pasteboard still holds this exact session — matching both
    /// the text and the UUID, not just `changeCount`, so a copy made during the paste
    /// window is left untouched.
    private func restoreIfStillOurs(text: String,
                                    sessionID: String,
                                    snapshot: [[(NSPasteboard.PasteboardType, Data)]],
                                    to pasteboard: NSPasteboard) {
        let stillOurs = pasteboard.string(forType: .string) == text
                     && pasteboard.string(forType: sessionType) == sessionID
        guard stillOurs else { return }

        pasteboard.clearContents()
        guard !snapshot.isEmpty else { return }
        pasteboard.writeObjects(snapshot.map { pairs in
            let item = NSPasteboardItem()
            for (type, data) in pairs {
                item.setData(data, forType: type)
            }
            return item
        })
    }

    // MARK: - Synthetic ⌘V

    /// Posts ⌘V on the HID tap. Uses the physical V key code (0x09) so keyboard
    /// layouts that remap letters onto Command still paste. Command is released with
    /// cleared flags so the modifier does not leak into subsequent events.
    private func postCommandV() async -> Bool {
        let source = CGEventSource(stateID: .privateState)
        guard let cmdDown = CGEvent(keyboardEventSource: source, virtualKey: Self.keyCommand, keyDown: true),
              let vDown   = CGEvent(keyboardEventSource: source, virtualKey: Self.keyV, keyDown: true),
              let vUp     = CGEvent(keyboardEventSource: source, virtualKey: Self.keyV, keyDown: false),
              let cmdUp   = CGEvent(keyboardEventSource: source, virtualKey: Self.keyCommand, keyDown: false)
        else { return false }

        cmdDown.flags = .maskCommand
        vDown.flags = .maskCommand
        vUp.flags = .maskCommand

        cmdDown.post(tap: .cghidEventTap)
        try? await Task.sleep(nanoseconds: Self.interEventDelay)
        vDown.post(tap: .cghidEventTap)
        try? await Task.sleep(nanoseconds: Self.interEventDelay)
        vUp.post(tap: .cghidEventTap)
        try? await Task.sleep(nanoseconds: Self.interEventDelay)
        cmdUp.post(tap: .cghidEventTap)
        return true
    }
}
